### ISSUE TITLE
kj version has wrong number of lines

### ISSUE THREAD

**Issue by dlovemore** [maxlit/grepbible#1]
kj version has 31092 lines instead of the usual 31102

**Comment by dlovemore** [comment]
~/grepbible_data $ grep -rn '[0-9]' kj 
kj/Joshua/21.txt:2:And they spake unto them at Shiloh in the land of Canaan, saying, The LORD commanded by the hand of Moses to give us cities to dwell in, with the suburbs thereof for our cattle. 3And the children of Israel gave unto the Levites out of their inheritance, at the commandment of the LORD, these cities and their suburbs.
kj/Luke/12.txt:3:Therefore whatsoever ye have spoken in darkness shall be heard in the light; and that which ye have spoken in the ear in closets shall be proclaimed upon the housetops. 4And I say unto you my friends, Be not afraid of them that kill the body, and after that have no more that they can do.
kj/Luke/12.txt:51:For from henceforth there shall be five in one house divided, three against two, and two against three. 53The father shall be divided against the son, and the son against the father; the mother against the daughter, and the daughter against the mother; the mother in law against her daughter in law, and the daughter in law against her mother in law.
kj/Luke/16.txt:20:And there was a certain beggar named Lazarus, which was laid at his gate, full of sores, 21And desiring to be fed with the crumbs which fell from the rich man's table: moreover the dogs came and licked his sores.
kj/Luke/6.txt:44:For every tree is known by his own fruit. For of thorns men do not gather figs, nor of a bramble bush gather they grapes. 45A good man out of the good treasure of his heart bringeth forth that which is good; and an evil man out of the evil treasure of his heart bringeth forth that which is evil: for of the abundance of the heart his mouth speaketh.
kj/1 Chronicles/1.txt:9:And the sons of Cush; Seba, and Havilah, and Sabta, and Raamah, and Sabtecha. And the sons of Raamah; Sheba, and Dedan. 10And Cush begat Nimrod: he began to be mighty upon the earth. 11And Mizraim begat Ludim, and Anamim, and Lehabim, and Naphtuhim, 12And Pathrusim, and Casluhim, (of whom came the Philistines,) and Caphthorim. 13And Canaan begat Zidon his firstborn, and Heth,
kj/1 Chronicles/1.txt:30:And Abraham begat Isaac. The sons of Isaac; Esau and Israel. 35The sons of Esau; Eliphaz, Reuel, and Jeush, and Jaalam, and Korah.

**Comment by dlovemore** [comment]
The correct number of verses is 31102
You will observe 311/99 is an approximation to pi.
31102/9900 is a closer approximation to pi
31102/99=314.161616161616161... which reflects the weekly sabbath cycle of 6+1 days.
You will also observe 31102=2*15551, which is a palindromic prime

**Comment by maxlit** [comment]
> kj version has 31092 lines instead of the usual 31102

indeed, 3 books have different number of verses:

- Joshua:  {'observed': 657, 'expected': 658}
- 1 Chronicles:  {'observed': 937, 'expected': 942}
- Luke:  {'observed': 1147, 'expected': 1151}

thanks for raising the issue, I'll investigate

**Comment by maxlit** [comment]
Please run `gbib -d kj` in the terminal (the update of the package isn't necessary), the updated text should match the expected line numbers.
Also `grep -rn '[0-9]'`shouldn't generate any line for KJV anymore.
